# Model arguments
model_name_or_path: Qwen/Qwen2.5-Coder-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: open-r1/verifiable-coding-problems-python-1k
dataset_configs:
- all

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
do_eval: true
eval_strategy: 'no' #steps
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-Coder-3B-Open-R1-GRPO
hub_strategy: every_save
learning_rate: 1.0e-05
log_completions: true
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 1024
max_completion_length: 2048
max_steps: -1
num_generations: 7
num_train_epochs: 1
output_dir: data/Qwen2.5-Coder-3B-Open-R1-GRPO
overwrite_output_dir: true
per_device_train_batch_size: 2
push_to_hub: false #true
report_to:
- wandb
reward_funcs:
- format
- code
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
